export const FETCH_CAMPERS_BY_POINT_TYPE = 'FETCH_CAMPERS_BY_POINT_TYPE';
export const FETCH_CAMPERS_BY_POINT_TYPE_SUCCEEDED =
  'FETCH_CAMPERS_BY_POINT_TYPE_SUCCEEDED';
export const FETCH_CAMPERS_BY_POINT_TYPE_FAILED =
  'FETCH_CAMPERS_BY_POINT_TYPE_FAILED';
